### ISSUE TITLE
TermViewer permanently refreshing

### ISSUE THREAD

**Issue by etrobert** [AxelLavielle/BabelFish#2]
When launching BabelFish with --view 0 (TERMINAL viewer), the app keeps refreshing the screen every X seconds, which results in 
- a permanent 42% CPU usage in my case
- when a few message are printed, they get repeated over and over again.
The expected behaviour IMHO would be to "remember" the differences with the last print at each refresh (aka the number of new lines) and to only print those.

(I'd say you could use a `size_t new_lines;` in the Data structure).

**Comment by EliseLavielle** [comment]
Hey, the app is refreshing the screen every `--speed millisecond` as said in the usage & the README. If you want to have a permanent view and not a "moving screen" please use `--view 1` since it was made for it !

If what bothers you is the 42% CPU usage, it may be because you have a lot of logs to parse, which increase the time that the BabelFish takes to complete his task. I recommand you to add a bigger time in the `--speed` or to clean your logs with a `--delete`. You can also put a threshold of maximum lines to keep with `--line`.

I hope you understand that I won't refresh only when needed, because it costs actually more CPU usage during the average & best cases, didn't try for the worst but expect it to be approximately the same.
Not only the new lines are searched, this software have no memory of the precedent logs.

Have a good day, if there is another issue in continuation with your problem, please comment below, I won't close it until you said it's good for you.

**Comment by etrobert** [comment]
You could update the screen every `--speed millisecond` and still printing only the necessary informations to update it. "Refreshing" is something you do on ncurses or a windowed viewer but it is not fit for a terminal viewer. I had 42% CPU usage with 4 log messages. It wouldn't really cost more CPU usage, its a matter of updating a `size_t`, not with a search but with an increment when you update the `vector` in `Data`. I understand that you won't correct this aberrant behaviour, so I will update our fork accordingly, by replacing the "refresh" function by an "update" function which will only print what is necessary on the term viewer.

**Comment by EliseLavielle** [comment]
Hey, Remember that not only the new lines are searched, this software have no memory of what it searched precedently, and it doesn't search more than asked, Your point will work for a very specific case, which is:
- launching the program with `--view 0`
- having an increasing size of logs that does not go above the threshold (100 logs)
- not using the `--line` option
The method I could use to make the software work the way you want, would be to have a memory of what have been precedently searched, and to compare each lines to see where I stopped and only print the end of the lines (which means comparing all the lines between themselves, so adding a O(n²) complexity with n going up to the threshold, slowing down the software (or using more GPU).

If you have another method to correct this behavior, please let me know and I'll implement it if it doesn't affect the other behaviors !

**Comment by etrobert** [comment]
Yes it is absolutely out of the question to compare the line strings ofc.
I am not sure of it but it looks like you are going through the whole log file at every iteration of the main loop. You could maybe remember the `line` where you stopped and print only the lines from `max(0, line - lines_to_display)` to `line`, which would actually speed up the whole process, and for the TermViewer, you would just had to remember the `last_printed_line` and print the lines from `last_printed_line` to `line`. It is of course more complicated than that because of the rotates andd stuff but you get the idea.

BabelFish is a cool library, and at the moment I am using a very simplified handmade version of it mainly because of this issue for my debugging, which is a shame !

Also, I did change the template parameter in the overload of the stream operator `Log::operator<<(T t)` to `Log::operator<<(const T& t)`. This prevents copy and is actually needed when copy constructor are disabled.

**Comment by EliseLavielle** [comment]
Actually, going through the whole log file is made because of two reasons:
First, it's a file, not a buffer in my software, everyone can `rm`, `mv`, or affect the file, at any moment (even I am doing it, with the rotate, the delete, the line threshold, ...).
Then, for other views than 0, there is a live way to change what you want to display so I really need to reparse the whole file in those cases.

Why are you not using the view 1 ? It's better ! Actually the view 0 was made temporary to have a first version and to see what I was doing / use BabelFish even if not that goodlooking. It won't get that much features in the future, if you have any idea to implement / you want to add a feature, you can do it and merge with this repo, I'll be pleased to take in account your contribution !

And for the `Log::operator<<(T t)`... Woups.. Missed this one, I'll correct that for the next version !

**Comment by etrobert** [comment]
Yes it is a file subject to external modification, but any modification external from your application is an exception. In the normal use case, aka 95+% of the time, babelfish will be the only one handling it and you can remember where you're at, and upgrade those values accordingly when rotating and stuff, while exceptions like file missing could end up in a reset and a creation of a new file with a new index idk...

Actually I am not using the view 1 mainly because of an other issue that @huguespoiget should post soon, that -on MAC at least- the printed area does not refresh unless an event is perceived (mouse click, key pressed...), and even if I did, a termview is always handy to have for example to parse in a colouring/search script or such `babelfish -v 0 | sh colorscript.sh`.

I plan on adding an option to the C++ lib, maybe as a `#define` to be able to print directly on a given stream and not in a file just for punctual debugging reasons
