### ISSUE TITLE
Screen refresh frozen via tmux

### ISSUE THREAD

**Issue by huguespoiget** [AxelLavielle/BabelFish#3]
When I launch Babelfish in a tmux pane, the lines are frozen. Waiting for a mouse or keyboard event from my side to refresh (such as a mouse click).

I've this bug on Ubuntu 14.04 with tmux of version: 1.8

**Comment by EliseLavielle** [comment]
Hey, I'm currently searching for this issue. Could you please send me your environnement variable called "TERM" ? `echo $TERM` inside a tmux !

**Comment by EliseLavielle** [comment]
Okay, I reproduced the bug on my computer, searching for a solution right now, btw, it seems that curses and tmux are not big friends.

**Comment by huguespoiget** [comment]
Apparently there is another problem with Tmux when I click on "Trace" for example to not have them listed in the visual window of BabelFish it takes it in account for a while but quickly Trace information came back whereas I didn't took any action.
I suggest also as it sometimes taking some time to load the messages to change the background color of the label clicked that at least we know we've well clicked on the label.

**Comment by EliseLavielle** [comment]
Hey, I found that I had the problem not only on tmux, but also on normal usage, I will try to fix that, definitely from my program and not from tmux.

**Comment by EliseLavielle** [comment]
Hey, the problem should be solved in the last push.
For explanation of what was occurring:
- The speed of the program was larger than the time of the gameLoop
- The software was computing `timeout(ts - timestamp)`, ts being the timestamp of the beginning of the loop + the refreshing speed, resulting in a negative number.
- Ncurses is using unsigned to calculate the timeouts, resulting in the program looping on the long, instead of `timeout(-10)`, it resulted in `timeout(4294967286)`, so it waited for an event to continue.
I replaced in negative case by a `timeout(0)`, which solved the problem, thanks for using BabelFish !
